name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:

    name: ${{ matrix.toolchain }}-${{ matrix.build_type }}${{ matrix.disable_exception && '-noexcept' || '' }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        toolchain:
          - linux-gcc
          - macos-clang
          - windows-msvc
          - windows-mingw

        build_type:
          - Debug
          - Release

        disable_exception:
          - false
          - true

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc

          - toolchain: macos-clang
            os: macos-latest
            compiler: clang

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc
            env:
              BIN_SUFFIX: ".exe"

          - toolchain: windows-mingw
            os: windows-latest
            compiler: mingw
            env:
              BIN_SUFFIX: ".exe"
              CMAKE_OPTIONS: "-G \"MinGW Makefiles\""

    steps:
      - uses: actions/checkout@v4

      - name: Configure (${{ matrix.build_type }}${{ matrix.disable_exception && ' with CORO_DISABLE_EXCEPTION' || '' }})
        run: |
          if [ "${{ matrix.disable_exception }}" = "true" ]; then
            cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_FLAGS="-DCORO_DISABLE_EXCEPTION" ${{ matrix.env.CMAKE_OPTIONS }}
          else
            cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ${{ matrix.env.CMAKE_OPTIONS }}
          fi
        shell: bash

      - name: Build with ${{ matrix.compiler }}
        run: cmake --build build --config ${{ matrix.build_type }} -j

      - name: Windows-MSVC Compatible
        if: matrix.os == 'windows-latest' && matrix.compiler == 'msvc'
        working-directory: build
        run: Move-Item -Path .\${{ matrix.build_type }}\* -Destination .\

      - name: Test coro(verbose)
        working-directory: build
        run: |
          ./coro_task_verbose${{ matrix.env.BIN_SUFFIX }}

      - name: Test coro
        working-directory: build
        run: |
          ./coro_task${{ matrix.env.BIN_SUFFIX }}

      - name: Test mutex
        working-directory: build
        run: |
          ./coro_mutex${{ matrix.env.BIN_SUFFIX }}

      - name: Test channel
        working-directory: build
        run: |
          echo "skip"
          ./coro_channel${{ matrix.env.BIN_SUFFIX }}
