name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:

    name: ${{ matrix.toolchain }} ${{ matrix.build_type }} disable_exception:${{ matrix.disable_exception }} sanitize_address:${{ matrix.sanitize_address }} sanitize_thread:${{ matrix.sanitize_thread }}
    runs-on: ${{ matrix.os }}

    env:
      TSAN_OPTIONS: "suppressions=${{ github.workspace }}/.github/tsan_suppressions.txt"

    strategy:
      fail-fast: false

      matrix:
        toolchain:
          - linux-gcc
          - macos-clang
          - windows-msvc
          - windows-mingw

        build_type:
          - Debug
          - Release

        disable_exception:
          - OFF
          - ON

        sanitize_address:
          - OFF
          - ON

        sanitize_thread:
          - OFF
          - ON

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc

          - toolchain: macos-clang
            os: macos-latest
            compiler: clang

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc
            env:
              BIN_SUFFIX: ".exe"

          - toolchain: windows-mingw
            os: windows-latest
            compiler: mingw
            env:
              BIN_SUFFIX: ".exe"
              CMAKE_OPTIONS: "-G \"MinGW Makefiles\""

        exclude:
          - sanitize_address: ON
            sanitize_thread: ON

          - toolchain: windows-msvc
            sanitize_address: ON
          - toolchain: windows-msvc
            sanitize_thread: ON

          - toolchain: windows-mingw
            sanitize_address: ON
          - toolchain: windows-mingw
            sanitize_thread: ON

          - toolchain: macos-clang
            sanitize_address: ON
          - toolchain: macos-clang
            sanitize_thread: ON

    steps:
      - uses: actions/checkout@v4

      - name: Configure ${{ matrix.build_type }} disable_exception:${{ matrix.disable_exception }} sanitize_address:${{ matrix.sanitize_address }} sanitize_thread:${{ matrix.sanitize_thread }}
        run: |
          cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCORO_DISABLE_EXCEPTION=${{ matrix.disable_exception }} \
          -DCORO_ENABLE_SANITIZE_ADDRESS=${{ matrix.sanitize_address }} \
          -DCORO_ENABLE_SANITIZE_THREAD=${{ matrix.sanitize_thread }} \
          ${{ matrix.env.CMAKE_OPTIONS }}
        shell: bash

      - name: Build with ${{ matrix.compiler }}
        run: cmake --build build --config ${{ matrix.build_type }} -j

      - name: Windows-MSVC Compatible
        if: matrix.os == 'windows-latest' && matrix.compiler == 'msvc'
        working-directory: build
        run: Move-Item -Path .\${{ matrix.build_type }}\* -Destination .\

      - name: Test task(verbose)
        if: always()
        working-directory: build
        run: |
          ./coro_task_verbose${{ matrix.env.BIN_SUFFIX }}

      - name: Test task
        if: always()
        working-directory: build
        run: |
          ./coro_task${{ matrix.env.BIN_SUFFIX }}

      - name: Test mutex
        if: always()
        working-directory: build
        run: |
          ./coro_mutex${{ matrix.env.BIN_SUFFIX }}

      - name: Test condition_variable
        if: always()
        working-directory: build
        run: |
          ./coro_condition_variable${{ matrix.env.BIN_SUFFIX }}

      - name: Test condition_variable_mt
        if: always()
        working-directory: build
        run: |
          ./coro_condition_variable_mt${{ matrix.env.BIN_SUFFIX }}

      - name: Test channel
        if: always()
        working-directory: build
        run: |
          ./coro_channel${{ matrix.env.BIN_SUFFIX }}

      - name: Test when
        if: always()
        working-directory: build
        run: |
          ./coro_when${{ matrix.env.BIN_SUFFIX }}

      - name: Test multi_thread
        if: always()
        working-directory: build
        run: |
          ./coro_multi_thread${{ matrix.env.BIN_SUFFIX }}

      - name: Test multi_thread(use single thread)
        if: always()
        working-directory: build
        run: |
          ./coro_multi_thread_st${{ matrix.env.BIN_SUFFIX }}
